/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ODDEVEN_H_RPCGEN
#define _ODDEVEN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	int num1;
};
typedef struct number number;

#define ISODDEVEN 0x23451111
#define ISODDEVEN_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ODDEVEN 1
extern  int * oddeven_1(number *, CLIENT *);
extern  int * oddeven_1_svc(number *, struct svc_req *);
extern int isoddeven_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ODDEVEN 1
extern  int * oddeven_1();
extern  int * oddeven_1_svc();
extern int isoddeven_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);

#else /* K&R C */
extern bool_t xdr_number ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ODDEVEN_H_RPCGEN */
